// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDilSZAK9b_OSIr-o7H84jbkqJeFTvf0L4',
    appId: '1:511450282316:web:4e6dc5285c4bd6e20337e9',
    messagingSenderId: '511450282316',
    projectId: 'tuition-management-b7789',
    authDomain: 'tuition-management-b7789.firebaseapp.com',
    storageBucket: 'tuition-management-b7789.firebasestorage.app',
    measurementId: 'G-JBFBJYK980',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaFMISq9p0jGU5o_yyHVNZtQCzBCOpgoU',
    appId: '1:511450282316:ios:472eb53d8329a00d0337e9',
    messagingSenderId: '511450282316',
    projectId: 'tuition-management-b7789',
    storageBucket: 'tuition-management-b7789.firebasestorage.app',
    iosBundleId: 'com.example.tuitionApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaFMISq9p0jGU5o_yyHVNZtQCzBCOpgoU',
    appId: '1:511450282316:ios:472eb53d8329a00d0337e9',
    messagingSenderId: '511450282316',
    projectId: 'tuition-management-b7789',
    storageBucket: 'tuition-management-b7789.firebasestorage.app',
    iosBundleId: 'com.example.tuitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDilSZAK9b_OSIr-o7H84jbkqJeFTvf0L4',
    appId: '1:511450282316:web:054ba89ad021121a0337e9',
    messagingSenderId: '511450282316',
    projectId: 'tuition-management-b7789',
    authDomain: 'tuition-management-b7789.firebaseapp.com',
    storageBucket: 'tuition-management-b7789.firebasestorage.app',
    measurementId: 'G-CT56H4DK99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADqIScZ--Da9I4Z3wreFAhd7G2VVH-_qM',
    appId: '1:511450282316:android:d258c1b067109ad40337e9',
    messagingSenderId: '511450282316',
    projectId: 'tuition-management-b7789',
    storageBucket: 'tuition-management-b7789.firebasestorage.app',
  );
}
